### ISSUE TITLE
Decipher event initiator?

### ISSUE THREAD

**Issue by dotKev** [FancyGrid/FancyGrid#106]
Is there a way to differentiate between user-initiated events and events from page resize or initialization?

I'm needing to save column widths on [columnresize](https://fancygrid.com/api/events/columnresize), but the event fires on each column when initializing and when the page is resized. I want know if the user initiated it via drag-and-drop.

Additional context: If the user has NOT manually edited the width, I want to use flex layout, with no specified widths, otherwise capture the pixel value of the widths (it won't be fully responsive then, but I don't know any way around that issue.)

**Comment by MikhailTatsky** [comment]
Thank you for your question.
I will try to answer on your question during day.

**Comment by MikhailTatsky** [comment]
@dotKev 
" but the event fires on each column when initializing and when the page is resized."
 I could not replicate it.
This event should be fired only when user change column width by self.
May I ask you to coordinate with me over Slack(you should have access)?
Maybe to try TeamViewer that to get your case.

"I want to use flex layout, with no specified widths, otherwise capture the pixel value of the widths"
We have flex for columns.
https://fancygrid.com/api/config/columns/flex
But it will be applied only on start.
We time to time think about upgrading it.
If we will add in column menu, item to resize columns, will it help?
It would be good to get your ideas about how it should work.

**Comment by dotKev** [comment]
I can't recreate the issue in a jsFiddle, so it appears to just be my implementation. Thanks!

**Comment by dotKev** [comment]
I was incorrect. I was able to recreate this. Using the `flex` parameter seems to initiate the `columnresize` event on init and screen resize. Is there any way to detect whether it was a user event vs. resize/init?

https://jsfiddle.net/dotkev/wvby9z1o/

**Comment by MikhailTatsky** [comment]
Thank you for good example.
It is bug.
We will try to fix it ASAP.

**Comment by MikhailTatsky** [comment]
@dotKev 
 Just did release with fix of this issue.
Please, check it out.

**Comment by dotKev** [comment]
Excellent. This resolved my issue. Thank you.
