### ISSUE TITLE
Can I use multi-line text in cell?

### ISSUE THREAD

**Issue by SoheeP** [FancyGrid/FancyGrid#156]
Hi, there.
I want to write multi line text in cell, like excel. But I cannot found related event, method or config.
I think `change` event is keyboard event, but that was mouse event. So I don't know what can I do.
How to use multi-line text in cell?

**Comment by MikeTatsky** [comment]
@SoheeP 
Thank you for your question.

We have column `type: 'text'` for multi-lines.
https://fancygrid.com/api/columns/text
https://fancygrid.com/samples/rows/autoheight
https://fancygrid.com/samples/columns/column-image-text

**Comment by SoheeP** [comment]
@MikeTatsky 

Thanks! 
I check my `fancygrid` config after I saw your links, I was setting was set to `string`. 😅
I almost solve my problem, but I still have a problem.
I try to add column config `editable: true` and write text, but I can't use `enter` key instead of `<br/>` .
Can I use specific key or combination(like `enter` key or `alt` + `enter` key) instead of writing `<br />` ?

**Comment by MikeTatsky** [comment]
@SoheeP 

The problem is that `text` in our case in fact is just long string that will be auto multilined by css propeties.
And as you mentioned, to force multiline it requires to use `<br>`, so it requires to intercept `alt+enter` and insert '<br>'.
At the moment, this feature is absent. We will think how to do it better and try to add in next release.

**Comment by SoheeP** [comment]
@MikeTatsky 
Okay, I'll look forward to it. :) Thanks!

**Comment by MikeTatsky** [comment]
@SoheeP 
 We just did new release.
You can try Shift+Enter.
It is not `<br>` but we hope it will suit.
