### ISSUE TITLE
Export to Excel

### ISSUE THREAD

**Issue by surfcoders** [FancyGrid/FancyGrid#77]
Hi @MikhailTatsk.  I have two questions:

1. What options are available when you export to Excel?  Currently this is all I see on your API documentation:
`    grid.exportToExcel({
        fileName: 'My Excel',
        header: true
    });
`
Looking at Infragistic's grid, they have more options for setting the Excel export.

2. Looks like by default, it only exports the current displayed rows on the grid.  Is there a way to export everything?

Thanks!

Nelson

**Comment by MikhailTatsky** [comment]
Hi @surfcoders 
At the moment our excel export is light and does not provide many options.
I hope in future we could extend it.

**Comment by MikhailTatsky** [comment]
Sorry for very delayed answer.
During these years we extended export functionality.
You can study it here
https://fancygrid.com/api/methods/exporttoexcel

It does not provide many options but still it is better that it was.
We do not plan to add styling and some very complex cases for export in the nearest future since none of our commercial clients need it.
