### ISSUE TITLE
subTBar or bbar do not show with Fancy Form Tabs

### ISSUE THREAD

**Issue by jesal-bhowmick** [FancyGrid/FancyGrid#91]
https://jsfiddle.net/w9xu7gyb/1/

**Comment by MikhailTatsky** [comment]
Hi Jesal,
yes sorely it is not implemented for FancyTab.

**Comment by MikhailTatsky** [comment]
Sorry for very delayed answer.
1 - In sample you provided, it is used our primitive case for form.
2 - There is more extended way to work with tabs.
Here is sample
https://jsfiddle.net/fancygrid/3qpmzsah/
Every tab can have `tbar`, `subTBar`, `buttons`, `bbar`.
But global container(FancyTab) can not have bars.
3 - All these issues with tabs is not our priority. Our priority is grid.
We do not plan to add in FancyTab bars on main container since none of our commercial clients need it.
